FROM debian:stable-slim
RUN apt-get update
RUN apt-get install python -y
RUN apt-get install node-gyp -y
RUN apt-get install curl -y

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 14.19.0

RUN mkdir -p ${NVM_DIR}

ENV WORK_DIR /app
RUN mkdir -p ${WORK_DIR}

WORKDIR ${WORK_DIR}

#COPY ./ ${WORK_DIR}/



RUN cd ${NVM_DIR}; \
 curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash \
 && . $NVM_DIR/nvm.sh \
 && nvm install $NODE_VERSION \
 && nvm alias default $NODE_VERSION \
 && nvm use default 


RUN ln -s ${NVM_DIR}/versions/node/v${NODE_VERSION}/bin/npm /bin/npm
RUN ln -s ${NVM_DIR}/versions/node/v${NODE_VERSION}/bin/node /bin/node

RUN cd ${WORK_DIR}
RUN npm i -g @nestjs/cli
RUN npm install
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH

EXPOSE 3000
